kind: Service
apiVersion: v1
metadata:
  name: amq-broker-hdls-svc
spec:
  type: NodePort
  ports:
    - name: amq-broker-hdls-svc8161
      protocol: TCP
      port: 8161
      targetPort: 8161
    - name: amq-broker-hdls-svc61616
      protocol: TCP
      port: 61616
      targetPort: 61616
      nodePort: 32000
  selector:
    app: amq-broker